config/routes.rb
Rails.application.routes.draw do

  get 'payment_methods' => "payment_methods#index"
  get 'set_method' => "payment_methods#set_method"
  get 'register_succesfull' => "register#index"
  resources :transactions
  get "/status_transactions", to: "transactions#status"
  resources :rates
  resources :banks
  
  devise_for :users, :controllers => { registrations: 'registrations' }, :path_names => { :sign_up => "register_or_login", :sign_in => "login_or_register" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/dhasboard' => "home#index", :as => :user_root
 
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  def index
  end

  def set_method
    @bank = Bank.new
  end
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/views/payment_methods/index.html.erb
<h4>Mis metodos para recibir pagos</h4>
<div class="row mb-3">
    <%if current_user.banks.count <= 0%>
    <div class="container">
        <div class="alert alert-primary alert-dismissible fade show mt-3" role="alert">
            <strong>Hola!</strong> No tienes ningun metodo de pago registrado.
        </div>
    </div>
    <%else%>
    <!-- Tabla cuentas -->
    <div class="col-xl-10 col-lg-12">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col"><small class="font-weight-bold">Titular<small></th>
                        <th scope="col"><small class="font-weight-bold">Pais<small></th>
                        <th scope="col"><small class="font-weight-bold">Nro DNI<small></th>
                        <th scope="col"><small class="font-weight-bold">Banco<small></th>
                        <th scope="col"><small class="font-weight-bold">Nro Cuenta<small></th>
                    </tr>
                </thead>
                <tbody>
                    <% current_user.banks.each do |account_bank| %>
                    <tr class="shadow-sm">
                        <td class="align-middle"><span><%=account_bank.name.capitalize%> <%=account_bank.last_name.capitalize%></span></td>
                        <td class="align-middle"><img src="/img/paises/<%=account_bank.country.capitalize%>.svg" class="img-fluid rounded-circle avatar" alt="<%=account_bank.country.capitalize%>" title="<%=account_bank.country.capitalize%>"/></td>

                        <%part1 = account_bank.identidy[0, 2]%>
                        <%part2 = account_bank.identidy[-3,3]%> 
                        <td class="align-middle"><span class=""><%=part1 << "***" << part2%></span>
                        </td>
                        <td class="align-middle"><span class=""><%=account_bank.bank%></span>
                        </td>
                        <%part1 = account_bank.number_account[0, 4]%>
                        <%part2 = account_bank.number_account[-4,4]%> 
                        <td class="align-middle"><span class=""><%=part1 << "****" << part2%></span>
                        </td>
                        <!--Boton Modal-->
                        <td class="align-middle"><a href="#" class="badge badge-secondary" data-toggle="modal" data-target="#exampleModal<%=account_bank.id%>">Ver <i class="far fa-eye ml-2"></i></a></td>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal<%=account_bank.id%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel"><%=account_bank.name%></h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Pais: <%=account_bank.country %><br>
                                        Estado: <%=account_bank.state %><br>
                                        Identidad: <%=account_bank.identidy%><br>
                                        Banco: <%=account_bank.bank %><br>
                                        N° Cuenta: <%=account_bank.number_account %><br>
                                        Tipo de Cuenta: <%=account_bank.type_account %><br>
                                        Codigo del Banco: <%=account_bank.cod_bank%><br>
                                        Numero de Telefono: <%=account_bank.phone%>

                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>

                                    </div>
                                </div>
                            </div>
                        </div>

                        <td class="align-middle"><a rel="nofollow" data-method="delete" href="/banks/<%=account_bank.id%>" data-confirm="Esta segur@ de eliminar esta cuenta?" class="badge badge-danger">Eliminar <i class="fas fa-trash-alt ml-2"></i></a></td>
                    </tr>
                    <%end%>
                </tbody>
            </table>
        </div>
    </div>
    <%end%>
</div>
<!-- Fin tabla cuentas -->

<%= link_to 'Añadir Cuenta', set_method_path, class:"btn btn-success mb-5" %>

app/views/payment_methods/set_method.html.erb
<div class="row justify-content-center mt-5">
    <div class="col-5 was-validated text-center">
        <label for="validationCountry" class="">Elije el pais donde te gustaria enviar remesas</label>
        <select class="custom-select" id="validationCountry" onChange="validarSelectPais(this)" required>
            <option selected disabled value="">Elegir...</option>
            <option value="Argentina">Argentina</option>
            <option value="Brasil">Brasil</option>
            <option value="Chile">Chile</option>
            <option value="Colombia">Colombia</option>
            <option value="Ecuador">Ecuador</option>
            <option value="España">España</option>
            <option value="Panama">Panama</option>
            <option value="Peru">Peru</option>
            <!--<option value="Portugal">Portugal</option>-->
            <option value="USA">USA</option>
            <option value="Venezuela">Venezuela</option>
        </select>
        <div class="invalid-feedback">Elige una opcion</div>
    </div>
</div>

<!--Metodos de Pago de Argentina-->
<div class="row justify-content-center mt-3 d-none" id="MethodsArgentina">
    <div class="col-5 was-validated text-center">
        <label for="validationMethodsArgentina" class="">Elije un metodo de pago</label>
        <select class="custom-select" id="validationMethosArgentina" onChange="modifyEnlace(this)" required>
            <option selected disabled value="">Elegir...</option>
            <option value="banks">Cuenta Bancaria</option>
        </select>
        <div class="invalid-feedback">Elige una opcion</div>
    </div>
</div>

<!--Metodos de Pago de Brasil-->
<div class="row justify-content-center mt-3 d-none" id="MethodsBrasil">
    <div class="col-5 was-validated text-center">
        <label for="validationMethodsBrasil" class="">Elije un metodo de pago</label>
        <select class="custom-select" id="validationMethosBrasil" required>
            <option selected disabled value="">Elegir...</option>
            <option value="/banks/new">Brubank</option>
            <option value="banks">Galicia</option>
        </select>
        <div class="invalid-feedback">Elige una opcion</div>
    </div>
</div>

<div class="row justify-content-center mt-3 d-none" id="cajaEnlace">
    <div class="col-5 was-validated text-center">
        <a class="btn btn-success" href="" id="enlace">Continuar</a>
    </div>
</div>

<script>
    function validarSelectPais(select) {
        switch (select.value) {
            case "Argentina":
                argentinaMethods = document.getElementById("MethodsArgentina");
                argentinaMethods.classList.remove("d-none");
                break;

            default:
                break;
        }
    }
    function modifyEnlace(select) {
        switch (select.value) {
            case "banks":
                enlace = document.getElementById("enlace");
                enlaceCaja = document.getElementById("cajaEnlace");
                country = document.getElementById("validationCountry");

                enlaceCaja.classList.remove("d-none");
                enlace.href = "/banks/new?country=".concat(country.value);
                break;
        
            default:
                break;
        }
    }
</script>