config/routes.rb
Rails.application.routes.draw do

  get 'payment_methods' => "payment_methods#index"
  get 'set_method' => "payment_methods#set_method"
  get 'register_succesfull' => "register#index"
  resources :transactions
  get "/status_transactions", to: "transactions#status"
  resources :rates
  resources :banks
  
  devise_for :users, :controllers => { registrations: 'registrations' }, :path_names => { :sign_up => "register_or_login", :sign_in => "login_or_register" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/dhasboard' => "home#index", :as => :user_root
 
end

app/models/bank.rb
class Bank < ApplicationRecord
   belongs_to :user
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:edit, :update]

  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1
  # GET /banks/1.json
  #def show
  #end

  # GET /banks/new
  def new
    @bank = Bank.new
    @name = params[:name]
  end

  # GET /banks/1/edit
  #def edit
  #end

  # POST /banks
  # POST /banks.json
  def create
    @bank = current_user.banks.create(bank_params)
    
    respond_to do |format|
      if @bank.save
        format.html { redirect_to banks_path, notice: 'Cuenta registrada con exito.' }
        format.json { render :show, status: :created, location: @bank }
      else
        format.html { render :new }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end  
  end

  # PATCH/PUT /banks/1
  # PATCH/PUT /banks/1.json
  #def update
  #  respond_to do |format|
  #    if @bank.update(bank_params)
  #      format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
  #      format.json { render :show, status: :ok, location: @bank }
  #    else
  #      format.html { render :edit }
  #      format.json { render json: @bank.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /banks/1
  # DELETE /banks/1.json
  def destroy
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to payment_methods_url, notice: 'Cuenta eliminada con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:name, :last_name, :identidy, :country, :state, :bank, :number_account, :type_account, :cod_bank, :phone)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_form.html.erb
<div class="mt-5">
    <%= form_with(model: bank, local: true) do |form| %>
    <% if bank.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(bank.errors.count, "error") %> impide(n) que esta cuenta sea guardada:</h2>

        <ul>
            <% bank.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
    <div class="field">
        <h6>* : Campos Obligatorios</h6>
    </div>

    <!--Nombre y Apellido-->
    <div class="form-row field my-3">
        <div class="col-6 col-md-4 mb-2">
            <label>Pais *</label>
            <input class="form-control text-capitalize" value="<%=params[:country]%>" name="bank[country]" readonly>
        </div>

        <div class="col-4 mb-2">
            <label for="validationName">Primer Nombre *</label>

            <input type="text" class="form-control text-capitalize is-invalid" id="validationName" name="bank[name]" oninput="return soloLetras(this)" autofocus="autofocus" maxlength="12" value="<%=params[:name]%>" required>
            <div class="invalid-feedback">
                Ingrese solo letras
            </div>
        </div>

        <div class="col-4 mb-2">
            <label for="validationLastName">Primer Apellido *</label>

            <input type="text" class="form-control text-capitalize is-invalid" id="validationLastName" name="bank[last_name]" maxlength="12" oninput="return soloLetras(this)" required>
            <div class="invalid-feedback">
                Ingrese solo letras
            </div>
        </div>
    </div>

    <!--DNI y Banco-->
    <div class="form-row field mb-3">
        <div class="col-12 col-md-6 mb-2">
            <label for="validationDNI">Nro DNI *</label>
            <input class="form-control is-invalid" id="validationDNI" type="text" maxlength="12" oninput="return soloNumeros(this)" name="bank[identidy]" required></input>
            <div class="invalid-feedback">
                Ingrese solo numeros
            </div>
        </div>

        <div class="col-6 mb-2">
            <label>Banco *</label>

            <select class="custom-select is-invalid" name="bank[bank]" onChange="validarSelect(this)" required>
                <option selected disabled value="">Elegir...</option>
                <%if params[:country] === "Argentina"%>
                <option value="Brubank">Brubank</option>
                <option value="Galicia">Galicia</option>
                <%end%>
            </select>
            <div class="invalid-feedback">Elige una opcion</div>
        </div>
    </div>

    <!--Banco-->
    <div class="form-row field mb-3">        

        <div class="col-4 mb-2">
            <label>Tipo de cuenta *</label>

            <select class="custom-select is-invalid" name="bank[type_account]" onChange="validarSelect(this)" required>
                <option selected disabled value="">Elegir...</option>
                <option value="Ahorro">Ahorro</option>
                <option value="Corriente">Corriente</option>
            </select>
            <div class="invalid-feedback">Elige una opcion</div>
        </div>

        <div class="col-12 col-md-8 mb-2">
            <label for="validationNumberAccount">Nro Cuenta *</label>
            <input class="form-control is-invalid" id="validationNumberAccount" type="text" maxlength="20" oninput="return soloNumeros(this)" name="bank[number_account]" required></input>
            <div class="invalid-feedback">
                Ingrese solo numeros
            </div>
        </div>
    </div>

    <div class="actions">
        <%= form.submit "Guardar", class:"btn btn-success mt-3 mb-5" %>
        <%= link_to 'Volver', banks_path, class:"btn btn-success mt-3 mb-5 float-right" %>
    </div>
    <% end %>
</div>

<script src="/js/vistas/script-form-for-campos.js"></script>

app/views/banks/edit.html.erb
<h1>Editing Bank</h1>

<%= render 'form', bank: @bank %>

<%= link_to 'Show', @bank %> |
<%= link_to 'Back', banks_path %>

app/views/banks/new.html.erb
<div class="alert alert-primary" role="alert">
    <strong class="text-capitalize">Hola <%=current_user.name%>!</strong> Registra los datos solicitados de la cuenta bancaria que deseas registrar. Debes llenar los campos obligatorios correctamente, los demas son opcionales.
</div>

<h3 class="">Registrar Nueva Cuenta</h3>

<%= render 'form', bank: @bank %>

app/views/banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bank.name %>
</p>

<p>
  <strong>Identidy:</strong>
  <%= @bank.identidy %>
</p>

<p>
  <strong>Country:</strong>
  <%= @bank.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @bank.state %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @bank.bank %>
</p>

<p>
  <strong>Number account:</strong>
  <%= @bank.number_account %>
</p>

<p>
  <strong>Type account:</strong>
  <%= @bank.type_account %>
</p>

<p>
  <strong>Cod bank:</strong>
  <%= @bank.cod_bank %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @bank.phone %>
</p>

<%= link_to 'Edit', edit_bank_path(@bank) %> |
<%= link_to 'Back', banks_path %>