config/routes.rb
Rails.application.routes.draw do

  get 'payment_methods' => "payment_methods#index"
  get 'set_method' => "payment_methods#set_method"
  get 'register_succesfull' => "register#index"
  resources :transactions
  get "/status_transactions", to: "transactions#status"
  resources :rates
  resources :banks
  
  devise_for :users, :controllers => { registrations: 'registrations' }, :path_names => { :sign_up => "register_or_login", :sign_in => "login_or_register" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/dhasboard' => "home#index", :as => :user_root
 
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
    @banks = Bank.all
  end

  def status
    @transaction = Transaction.all
  end
  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    if User.find(1).is_admin?
      @admin_banks = User.find(1).banks
    end
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = current_user.transactions.create(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:monto, :metodo, :account_destinity, :payment_bank)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
<% if transaction.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

    <ul>
        <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>


<h3 class="text-success mt-3">Formulario de Envio</h3>

<div class="form-row field">
    <div class="col-sm-6 col-md-4">
        <label for="validationDefault1">Cuenta donde realizaste el pago</label>
        <select class="custom-select" id="validationDefault1" name="transaction[payment_bank]" required>
            <option selected disabled value="">Elige una opcion...</option>
            <%admin_banks.each do |admin_bank|%>
            <%if admin_bank.country === current_user.country%>
            <option value="<%=admin_bank.id%>"><%=admin_bank.bank%></option>
            <%end%>
            <%end%>

        </select>
    </div>

    <div class="col-sm-6 col-md-4">

    </div>
    <div class="col-sm-6 col-md-4">

        <%= form.label :monto %>
        <%= form.number_field :monto, step: 0.001 %>

    </div>


</div>

<div class="form-row field">
    <div class="col-sm-6 col-md-4">
        <label for="validationDefault2">Metodo de Pago</label>
        <select class="custom-select" id="validationDefault2" name="transaction[metodo]" required>
            <option selected disabled value="">Elige una opcion...</option>
            <option value="Transferencia">Transferencia</option>
            <option value="Deposito Directo">Deposito Directo</option>
            <option value="Deposito Cajero Automatico">Deposito Cajero Automatico</option>
            <option value="Deposito Por Loterica">Deposito Por Loterica</option>
        </select>
    </div>
    <div class="col-sm-6 col-md-4">

    </div>
    <div class="col-sm-6 col-md-4">
        <label for="validationDefault3">Cuenta Destino</label>
        <select class="custom-select" id="validationDefault3" name="transaction[account_destinity]" required>
            <option selected disabled value="">Elige una opcion...</option>
            <%current_user.banks.each do |bank_user|%>
            <option value="<%=bank_user.id%>"><%=bank_user.bank%></option>
            <%end%>
        </select>
    </div>
</div>

<div class="actions">
    <%= form.submit "Enviar Dinero", class:"btn btn-primary mt-3"%>
</div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<div class="container margin-top bg-nav">
    <h2 class="text-success">Transacciones Realizadas</h2>
    <table class="table table-hover mt-5">
        <thead>
            <tr>
                <th scope="col">Fecha y Hora</th>
                <th scope="col">Nombre</th>
                <th scope="col">Resumen de Cuenta</th>
                <th scope="col">Pais</th>
                <th scope="col">Monto</th>
            </tr>
        </thead>
        <tbody>
            <% @transactions.each do |transaction| %>
            <tr>

                <th scope="row"><%=transaction.created_at%></th>
                <%current_user.banks.each do |bank|%>
                <%if bank.id === transaction.account_destinity%>
                <td><%=bank.name%></td>
                <td><%=bank.number_account%></td>
                <td><%=bank.country%></td>
                <%end%>
                <%end%>
                <td><%=transaction.monto%></td>
        
            </tr>
            <%end%>
        </tbody>
    </table>
    <div class="my-5">
    <button class="btn btn-primary mb-5">Yess</button>
    </div>
</div>

app/views/transactions/new.html.erb
<div class="container bg-nav margin-top">

    <h2>Enviar Dinero</h2>

    <h5>Cuentas Registradas</h5>
    <%current_user.banks.each do |bank|%>

    <div class="col-xl-6">
        <b><span><%=bank.name%></span></b>
        <span><%=bank.number_account%></span>
    </div>
    <%end%>

    <h5>Cuentas de Otacar Cambios</h5>
    <%@admin_banks.each do |admin_banks|%>
    <div class="col-xl-6">
        <b><span><%=admin_banks.name%></span></b>
        <span><%=admin_banks.number_account%></span>
    </div>
    <%end%>

    <%= render 'form', {transaction: @transaction, admin_banks: @admin_banks} %>


</div>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Monto:</strong>
  <%= @transaction.monto %>
</p>

<p>
  <strong>Metodo:</strong>
  <%= @transaction.metodo %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/status.html.erb
<div class="container margin-top bg-nav">
    <h2 class="py-2">Estatus de mis transacciones</h2>
    <div class="row text-success mt-5">
        <div class="col-sm-6">
            <h4>Id Transaccion</h4>
        </div>
        <div class="col-sm-6">
            <h4>Status</h4>
        </div>
    </div>
    <%@transaction.each do |trans|%>
    <%if current_user.id === trans.user_id%>
    <div class="row text-primary">
        <div class="col-sm-6">
            <span><%=trans.id%></span>
        </div>
        <div class="col-sm-6">
            <span><%=trans.status%></span>
        </div>

    </div>
    <%end%>
    <%end%>
</div>