config/routes.rb
Rails.application.routes.draw do

  get 'payment_methods' => "payment_methods#index"
  get 'set_method' => "payment_methods#set_method"
  get 'register_succesfull' => "register#index"
  resources :transactions
  get "/status_transactions", to: "transactions#status"
  resources :rates
  resources :banks
  
  devise_for :users, :controllers => { registrations: 'registrations' }, :path_names => { :sign_up => "register_or_login", :sign_in => "login_or_register" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/dhasboard' => "home#index", :as => :user_root
 
end

app/models/rate.rb
class Rate < ApplicationRecord
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_rate, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(rate_params)

    respond_to do |format|
      if @rate.save
        format.html { redirect_to rates_path, notice: 'Registro de tasas creado con exito.' }
        format.json { render :show, status: :created, location: @rate }
      else
        format.html { render :new }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1
  # PATCH/PUT /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to rates_path, notice: 'Tasas guardadas con exito.' }
        format.json { render :show, status: :ok, location: @rate }
      else
        format.html { render :edit }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate.destroy
    respond_to do |format|
      format.html { redirect_to rates_url, notice: 'Rate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rate_params
      params.require(:rate).permit(:country, :moneda, :monto_oferta, :rate_brasil, :rate_brasil_min, :rate_chile, :rate_chile_min, :rate_ecuador, :rate_ecuador_min, :rate_españa, :rate_españa_min, :rate_panama, :rate_panama_min, :rate_peru, :rate_peru_min, :rate_portugal, :rate_portugal_min, :rate_usa, :rate_usa_min, :rate_venezuela, :rate_venezuela_min) 
    end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/rates/_form.html.erb
<%= form_with(model: rate, local: true, :html => {:class => "was-validated"}) do |form| %>
<% if rate.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

    <ul>
        <% rate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="row field">
    <%if @vista === "new"%>
    <div class="col-12 col-md-4 mt-2">
        <%= form.label :country, "Pais" %>
        
        <select class="custom-select" name="rate[country]" id="rate_country" required>
            <option selected disabled value="">Elegir...</option>
            <option value="Brasil">Brasil</option>
            <option value="Chile">Chile</option>
            <option value="Ecuador">Ecuador</option>
            <option value="España">España</option>
            <option value="Panama">Panama</option>
            <option value="Peru">Peru</option>
            <option value="Portugal">Portugal</option>
            <option value="USA">USA</option>
            <option value="Venezuela">Venezuela</option>
        </select>
        <div class="invalid-feedback">Elige una opcion</div>
    </div>

    <%else%>
    <div class="col-12 col-md-4 mt-2">
        <%= form.label :country, "Pais" %>
        <input class="text-capitalize" id="rate_country" value="<%if rate.country.capitalize === "Usa"%><%=rate.country.upcase%><%else%><%=rate.country.capitalize%><%end%> " readonly>
    </div>
    <%end%>

    <div class="col-12 col-md-4 mt-2">
        <%= form.label :monto_oferta, "Monto Oferta" %>
        <%= form.text_field :monto_oferta, id:"montoOferta"%>
    </div>

    <div class="col-12 col-md-4 mt-2">
        <%= form.label :moneda, "Moneda" %>
        <%= form.text_field :moneda, id:"moneda", readonly: :readonly %>
    </div>
</div>

<%if @vista === "new" || rate.country.capitalize != "Brasil"%>
<div class="" id="Brasil">
    <h3 class="mt-3 text-success">Brasil</h3>
    <div class="row field">

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_brasil, "Sin tasa minima" %>
            <%= form.text_field :rate_brasil, required: :required, oninput:"return inputNumber(event)"%>
        </div>

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_brasil_min, "A partir de" %><span class="text-primary font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%= rate.monto_oferta %> <%end%></span><span class="text-primary  font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%=rate.moneda%><%end%></span>
            <%= form.text_field :rate_brasil_min, oninput:"return inputNumber(event)" %>
        </div>
    </div>
</div>
<%end%>

<%if @vista === "new" || rate.country.capitalize != "Chile"%>
<div class="" id="Chile">
    <h3 class="mt-3 text-success">Chile</h3>
    <div class="row field">

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_chile, "Sin tasa minima" %>
            <%= form.text_field :rate_chile, required: :required, oninput:"return inputNumber(event)"%>
        </div>

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_chile_min, "A partir de" %><span class="text-primary font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%= rate.monto_oferta %> <%end%></span><span class="text-primary  font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%=rate.moneda%><%end%></span>
            <%= form.text_field :rate_chile_min, oninput:"return inputNumber(event)" %>
        </div>
    </div>
</div>
<%end%>

<%if @vista === "new" || rate.country.capitalize != "Ecuador"%>
<div class="" id="Ecuador">
    <h3 class="mt-3 text-success">Ecuador</h3>
    <div class="row field">

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_ecuador, "Sin tasa minima" %>
            <%= form.text_field :rate_ecuador, required: :required, oninput:"return inputNumber(event)"%>
        </div>

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_ecuador_min, "A partir de" %><span class="text-primary font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%= rate.monto_oferta %> <%end%></span><span class="text-primary  font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%=rate.moneda%><%end%></span>
            <%= form.text_field :rate_ecuador_min, oninput:"return inputNumber(event)" %>
        </div>
    </div>
</div>
<%end%>

<%if @vista === "new" || rate.country.capitalize != "España"%>
<div class="" id="España">
    <h3 class="mt-3 text-success">España</h3>
    <div class="row field">

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_españa, "Sin tasa minima" %>
            <%= form.text_field :rate_españa, required: :required, oninput:"return inputNumber(event)"%>
        </div>

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_españa_min, "A partir de" %><span class="text-primary font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%= rate.monto_oferta %> <%end%></span><span class="text-primary  font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%=rate.moneda%><%end%></span>
            <%= form.text_field :rate_españa_min, oninput:"return inputNumber(event)" %>
        </div>
    </div>
</div>
<%end%>

<%if @vista === "new" || rate.country.capitalize != "Panama"%>
<div class="" id="Peru">
    <h3 class="mt-3 text-success">Panama</h3>
    <div class="row field">

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_panama, "Sin tasa minima" %>
            <%= form.text_field :rate_panama, required: :required, oninput:"return inputNumber(event)"%>
        </div>

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_panama_min, "A partir de" %><span class="text-primary font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%= rate.monto_oferta %> <%end%></span><span class="text-primary  font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%=rate.moneda%><%end%></span>
            <%= form.text_field :rate_panama_min, oninput:"return inputNumber(event)" %>
        </div>
    </div>
</div>
<%end%>

<%if @vista === "new" || rate.country.capitalize != "Peru"%>
<div class="" id="Peru">
    <h3 class="mt-3 text-success">Peru</h3>
    <div class="row field">

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_peru, "Sin tasa minima" %>
            <%= form.text_field :rate_peru, required: :required, oninput:"return inputNumber(event)"%>
        </div>

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_peru_min, "A partir de" %><span class="text-primary font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%= rate.monto_oferta %> <%end%></span><span class="text-primary  font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%=rate.moneda%><%end%></span>
            <%= form.text_field :rate_peru_min, oninput:"return inputNumber(event)" %>
        </div>
    </div>
</div>
<%end%>

<%if @vista === "new" || rate.country.capitalize != "Portugal"%>
<div class="" id="Portugal">
    <h3 class="mt-3 text-success">Portugal</h3>
    <div class="row field">

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_portugal, "Sin tasa minima" %>
            <%= form.text_field :rate_portugal, required: :required, oninput:"return inputNumber(event)"%>
        </div>

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_portugal_min, "A partir de" %><span class="text-primary font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%= rate.monto_oferta %> <%end%></span><span class="text-primary  font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%=rate.moneda%><%end%></span>
            <%= form.text_field :rate_portugal_min, oninput:"return inputNumber(event)" %>
            
        </div>
    </div>
</div>
<%end%>

<%if @vista === "new" || rate.country.upcase != "USA"%>
<div class="" id="USA">
    <h3 class="mt-3 text-success">USA</h3>
    <div class="row field">

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_usa, "Sin tasa minima" %>
            <%= form.text_field :rate_usa, required: :required, oninput:"return inputNumber(event)"%>
            
        </div>

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_usa_min, "A partir de" %><span class="text-primary font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%= rate.monto_oferta %> <%end%></span><span class="text-primary  font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%=rate.moneda%><%end%></span>
            <%= form.text_field :rate_usa_min, oninput:"return inputNumber(event)" %>
        </div>
    </div>
</div>
<%end%>

<%if @vista === "new" || rate.country.capitalize != "Venezuela"%>
<div class="" id="Venezuela">
    <h3 class="mt-3 text-success">Venezuela</h3>
    <div class="row field">

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_venezuela, "Sin tasa minima" %>
            <%= form.text_field :rate_venezuela, required: :required, oninput:"return inputNumber(event)"%>
            
        </div>

        <div class="col-12 col-md-6 mt-2">
            <%= form.label :rate_venezuela_min, "A partir de" %><span class="text-primary font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%= rate.monto_oferta %> <%end%></span><span class="text-primary  font-weight-bold"><%if rate.monto_oferta != "0,00"%> <%=rate.moneda%><%end%></span>
            <%= form.text_field :rate_venezuela_min, oninput:"return inputNumber(event)" %>
        </div>
    </div>
</div>
<%end%>


<div class="actions mt-3">
    <%= form.submit "Guardar", class:"btn btn-success mb-5" %>
    <%= link_to 'Volver', :back, class:"btn btn-success mb-5 float-right"%>
</div>
<% end %>

<script src="/js/vistas/campos-numericos-format.js"></script>

app/views/rates/edit.html.erb
<h1 class="text-primary">Editar Tasa</h1>
<%@digit = 5%>
<%= render 'form', rate: @rate, collection: @digit %>

<%= render 'partials/scriptTasas',rate: @rate, collection: @digit%>

app/views/rates/index.html.erb
<h4 class="text-primary text-center mb-4">Tasas</h4>

<div class="row">
    <% @rates.each do |rate| %>

    <div class="col-12 col-sm-6 col-lg-3 mb-3">
        <div class="card border-success text-center m-auto" style="max-width: 13.5rem;">
            <div class="card-header bg-transparent border-success"><%if rate.country.capitalize === "Usa"%><%=rate.country.upcase%><%else%><%=rate.country.capitalize%><%end%> </div>
            <div class="card-body text-success">
                <h5 class="card-title"><%=rate.moneda%></h5>
            </div>
            <div class="card-footer bg-transparent border-success">
                
                    <!-- Button trigger modal -->
                    <a href="#" class="text-primary" data-toggle="modal" data-target="#exampleModal<%=rate.id%>">
                        <i class="far fa-eye" style="font-size:1.5em"></i>
                    </a>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal<%=rate.id%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-scrollable">
                            <div class="modal-content">

                                <div class="modal-header">
                                    <h5 class="modal-title text-success" id="exampleModalLabel">Tasas de <%if rate.country.capitalize === "Usa"%><%=rate.country.upcase%><%else%><%=rate.country.capitalize%><%end%> para envios a:</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <div class="card border-success mb-3 m-auto" style="max-width: 36rem;">

                                        <div class="card-header text-success text-center">
                                            <%@rate = rate%>
                                            <%= render "partials/tasas", collection: @rate %>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>

                                </div>
                            </div>
                        </div>
                    </div>

                    <a href="/rates/<%=rate.id%>/edit"><i class="fas fa-edit text-success ml-2" style="font-size:1.5em"></i></a>

                    <a data-confirm="Esta segur@ de eliminar esta cuenta?" rel="nofollow" data-method="delete" href="/rates/<%=rate.id%>" class="ml-2"><i class="fas fa-trash-alt text-danger" style="font-size:1.5em"></i></a>
                
            </div>
        </div>

    </div>
    <%end%>
</div>
<br>

<%= link_to 'Registrar Tasas', new_rate_path, class:"btn btn-success mb-2" %>

app/views/rates/new.html.erb
<h3 class="text-primary mb-4">Registrar Tasas</h3>
<%@digit = 3%>
<%@vista = "new"%>
<%= render 'form', rate: @rate, collection: @digit %>

<%= render 'partials/scriptTasas',rate: @rate, collection: @digit, collection: @vista%>

app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rate brasil:</strong>
  <%= @rate.rate_brasil %>
</p>


<p>
  <strong>Rate ecuador:</strong>
  <%= @rate.rate_ecuador %>
</p>

<p>
  <strong>Rate españa:</strong>
  <%= @rate.rate_españa %>
</p>

<p>
  <strong>Rate peru:</strong>
  <%= @rate.rate_peru %>
</p>

<p>
  <strong>Rate portugal:</strong>
  <%= @rate.rate_portugal %>
</p>

<p>
  <strong>Rate usa:</strong>
  <%= @rate.rate_usa %>
</p>

<p>
  <strong>Rate venezuela:</strong>
  <%= @rate.rate_venezuela %>
</p>

<%= link_to 'Edit', edit_rate_path(@rate) %> |
<%= link_to 'Back', rates_path %>